### ISSUE TITLE
Support for (nested) arrays

### ISSUE THREAD

**Issue by saschask** [miktam/key-del#8]
Would be nice to have support for keys to remove inside of (nested) arrays as well since arrays are also valid parts of a JSON object.

Example:

```
let data = {
    "myKey1": 123,
    "myKey2": true,
    "myKey3": {
        "myKey4": "foo",
        "myKey5": [
            {
                "myKey1": 456,
                "myKey6": null
            }
        ]
    }
};

let keyDel = require("key-del");
keyDel(data, "myKey1");
```

Result should be...

```
{
    "myKey2": true,
    "myKey3": {
        "myKey4": "foo",
        "myKey5": [
            {
                "myKey6": null
            }
        ]
    }
}
```

...but is...

```
{
    "myKey2": true,
    "myKey3": {
        "myKey4": "foo",
        "myKey5": [
            {
                "myKey1": 456,
                "myKey6": null
            }
        ]
    }
}
```

**Comment by miktam** [comment]
Interesting idea, will put it on the roadmap

**Comment by bateramos** [comment]
Hello,

I was trying to implement this, and discovery that its already implemented, but npm still gets a older version. Maybe adding a new release tag with the current changes will add this feature to everyone.

**Comment by miktam** [comment]
> I was trying to implement this, and discovery that its already implemented, but npm still gets a older version

what do you mean? where is it implemented?

**Comment by bateramos** [comment]
Sorry, I think I confuse things. On the npm, there is available a version that nested objects don't get the attribute removed, but this feature was implemented, but not released. I did not test nested arrays.

**Comment by iuliaL** [comment]
i've written this snippet:
https://gist.github.com/iuliaL/23236b8e452e2895adbeb639cf62027b

it only supports one key to delete at a time but it works for nested arrays too and supports DOT_SEPARATOR

maybe it's useful as a contribution

**Comment by sanchan** [comment]
I created a pull request for this here: https://github.com/miktam/key-del/pull/9
